// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingsService.Data;

#nullable disable

namespace TrainingsService.Migrations
{
    [DbContext(typeof(TrainingsDbContext))]
    partial class TrainingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TrainingsService.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instructor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Date");

                    b.HasIndex("Title");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "İSG",
                            CreatedAt = new DateTime(2025, 9, 11, 17, 58, 45, 4, DateTimeKind.Utc).AddTicks(834),
                            Date = new DateTime(2025, 9, 18, 17, 58, 45, 4, DateTimeKind.Utc).AddTicks(827),
                            Description = "İSG temel bilgileri, risk değerlendirmesi ve güvenlik kuralları",
                            Duration = 240,
                            Instructor = "İSG Uzmanı",
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Konferans Salonu",
                            Mandatory = true,
                            MaxParticipants = 50,
                            Title = "İş Sağlığı ve Güvenliği Temel Eğitimi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Yangın Güvenliği",
                            CreatedAt = new DateTime(2025, 9, 11, 17, 58, 45, 4, DateTimeKind.Utc).AddTicks(839),
                            Date = new DateTime(2025, 9, 25, 17, 58, 45, 4, DateTimeKind.Utc).AddTicks(837),
                            Description = "Yangın önleme, söndürme teknikleri ve acil durum prosedürleri",
                            Duration = 180,
                            Instructor = "İtfaiye Eri",
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Eğitim Merkezi",
                            Mandatory = true,
                            MaxParticipants = 30,
                            Title = "Yangın Güvenliği ve Acil Durum Eğitimi"
                        },
                        new
                        {
                            Id = 3,
                            Category = "İlk Yardım",
                            CreatedAt = new DateTime(2025, 9, 11, 17, 58, 45, 4, DateTimeKind.Utc).AddTicks(843),
                            Date = new DateTime(2025, 10, 2, 17, 58, 45, 4, DateTimeKind.Utc).AddTicks(841),
                            Description = "Temel ilk yardım teknikleri ve acil müdahale yöntemleri",
                            Duration = 360,
                            Instructor = "Doktor",
                            IsActive = true,
                            IsDeleted = false,
                            Location = "Sağlık Merkezi",
                            Mandatory = false,
                            MaxParticipants = 20,
                            Title = "İlk Yardım Eğitimi"
                        });
                });

            modelBuilder.Entity("TrainingsService.Entities.UserTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CertificateExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CertificateIssueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CertificatePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TrainingId")
                        .IsUnique();

                    b.ToTable("UserTrainings");
                });

            modelBuilder.Entity("TrainingsService.Entities.UserTraining", b =>
                {
                    b.HasOne("TrainingsService.Entities.Training", "Training")
                        .WithMany("UserTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");
                });

            modelBuilder.Entity("TrainingsService.Entities.Training", b =>
                {
                    b.Navigation("UserTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
