USE planning_db;

CREATE TABLE IF NOT EXISTS AnnualWorkPlans (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CompanyId INT NULL,
    Year INT NOT NULL,
    Category VARCHAR(200) NULL,
    SequenceNumber INT NULL,
    ActivityName VARCHAR(500) NOT NULL,
    RelatedLegislation VARCHAR(500) NULL,
    ActivityDescription TEXT NULL,
    Department VARCHAR(200) NULL,
    ResponsiblePerson VARCHAR(200) NULL,
    PlannedStartDate DATETIME NULL,
    PlannedEndDate DATETIME NULL,
    ActualStartDate DATETIME NULL,
    ActualEndDate DATETIME NULL,
    Budget VARCHAR(200) NULL,
    Resources TEXT NULL,
    Priority VARCHAR(50) NOT NULL DEFAULT 'Medium',
    Status VARCHAR(50) NOT NULL DEFAULT 'Planned',
    CompletionPercentage INT NULL,
    Notes TEXT NULL,
    January BOOLEAN NULL,
    February BOOLEAN NULL,
    March BOOLEAN NULL,
    April BOOLEAN NULL,
    May BOOLEAN NULL,
    June BOOLEAN NULL,
    July BOOLEAN NULL,
    August BOOLEAN NULL,
    September BOOLEAN NULL,
    October BOOLEAN NULL,
    November BOOLEAN NULL,
    December BOOLEAN NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
